Home work 6 (Oleg Zadniprovskyi)
p1v2/hillel-django-1 pull request #21
Opened 2023-03-13 14:25 UTC by gelono

2023-03-13 17:07 UTC, p1v2 requested changes
Pls check my comments

2023-03-13 17:07 UTC, p1v2 commented on books/tasks.py
> +        send_telegram_message(text, a.telegram_account_id)
what will happen if telegram_account_id is None? I believe your function will fail, but it shouldn't

2023-03-13 17:07 UTC, p1v2 commented on books/tasks.py
> +            send_telegram_message(text, author.telegram_account_id)
same here

2023-03-13 17:31 UTC, gelono commented on books/tasks.py
> +        send_telegram_message(text, a.telegram_account_id)
Yes, there is a lack of validation

2023-03-13 17:36 UTC, gelono commented on books/tasks.py
> +            send_telegram_message(text, author.telegram_account_id)
Row #64. Is this validation not enough? If it's True, the message will be sent. If it's False (None), the message won't be sent.

2023-03-13 17:48 UTC, p1v2 commented on books/tasks.py
> +            send_telegram_message(text, author.telegram_account_id)
aha, I see here. Ok, here it fine. then pls check my previous comment

2023-03-14 08:30 UTC, p1v2 approved these changes

2023-03-14 08:30 UTC, closed without merging